"use client";

import { SessionProvider } from "next-auth/react";
import AuthProvider from "./_context/auth_context";
import "./globals.css";
import { Inter } from "next/font/google";
import Home from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  console.log(children);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
